/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttorneyRouteImport } from './routes/attorney'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DashRouteImport } from './routes/dash'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as HuntRouteImport } from './routes/hunt'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as PacketRouteImport } from './routes/packet'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as RentRouteImport } from './routes/rent'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProtectIndexRouteImport } from './routes/protect.index'
import { Route as ProtectCrisisRouteImport } from './routes/protect.crisis'
import { Route as ProtectDashboardRouteImport } from './routes/protect.dashboard'
import { Route as ProtectFeesRouteImport } from './routes/protect.fees'
import { Route as ProtectIntakeRouteImport } from './routes/protect.intake'
import { Route as ProtectPacketRouteImport } from './routes/protect.packet'
import { Route as ProtectQuizRouteImport } from './routes/protect.quiz'
import { Route as RentIndexRouteImport } from './routes/rent.index'
import { Route as RentApplyRouteImport } from './routes/rent.apply'
import { Route as RentCalendarRouteImport } from './routes/rent.calendar'
import { Route as RentDeskRouteImport } from './routes/rent.desk'
import { Route as RentLeasesRouteImport } from './routes/rent.leases'
import { Route as RentPaymentsRouteImport } from './routes/rent.payments'
import { Route as RentWaitlistRouteImport } from './routes/rent.waitlist'
import { Route as RentWorkRouteImport } from './routes/rent.work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttorneyRoute = AttorneyRouteImport.update({
  id: '/attorney',
  path: '/attorney',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntRoute = HuntRouteImport.update({
  id: '/hunt',
  path: '/hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketRoute = PacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectIndexRoute = ProtectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectCrisisRoute = ProtectCrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectDashboardRoute = ProtectDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectFeesRoute = ProtectFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectIntakeRoute = ProtectIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectPacketRoute = ProtectPacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => ProtectRoute,
} as any)
const ProtectQuizRoute = ProtectQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => ProtectRoute,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RentRoute,
} as any)
const RentApplyRoute = RentApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => RentRoute,
} as any)
const RentCalendarRoute = RentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => RentRoute,
} as any)
const RentDeskRoute = RentDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => RentRoute,
} as any)
const RentLeasesRoute = RentLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => RentRoute,
} as any)
const RentPaymentsRoute = RentPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => RentRoute,
} as any)
const RentWaitlistRoute = RentWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => RentRoute,
} as any)
const RentWorkRoute = RentWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => RentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attorney': typeof AttorneyRoute
  '/connect': typeof ConnectRoute
  '/dash': typeof DashRoute
  '/houses': typeof HousesRoute
  '/hunt': typeof HuntRoute
  '/letters': typeof LettersRoute
  '/owners': typeof OwnersRoute
  '/packet': typeof PacketRoute
  '/protect': typeof ProtectRouteWithChildren
  '/rent': typeof RentRouteWithChildren
  '/search': typeof SearchRoute
  '/protect/crisis': typeof ProtectCrisisRoute
  '/protect/dashboard': typeof ProtectDashboardRoute
  '/protect/fees': typeof ProtectFeesRoute
  '/protect/intake': typeof ProtectIntakeRoute
  '/protect/packet': typeof ProtectPacketRoute
  '/protect/quiz': typeof ProtectQuizRoute
  '/rent/apply': typeof RentApplyRoute
  '/rent/calendar': typeof RentCalendarRoute
  '/rent/desk': typeof RentDeskRoute
  '/rent/leases': typeof RentLeasesRoute
  '/rent/payments': typeof RentPaymentsRoute
  '/rent/waitlist': typeof RentWaitlistRoute
  '/rent/work': typeof RentWorkRoute
  '/protect/': typeof ProtectIndexRoute
  '/rent/': typeof RentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attorney': typeof AttorneyRoute
  '/connect': typeof ConnectRoute
  '/dash': typeof DashRoute
  '/houses': typeof HousesRoute
  '/hunt': typeof HuntRoute
  '/letters': typeof LettersRoute
  '/owners': typeof OwnersRoute
  '/packet': typeof PacketRoute
  '/search': typeof SearchRoute
  '/protect/crisis': typeof ProtectCrisisRoute
  '/protect/dashboard': typeof ProtectDashboardRoute
  '/protect/fees': typeof ProtectFeesRoute
  '/protect/intake': typeof ProtectIntakeRoute
  '/protect/packet': typeof ProtectPacketRoute
  '/protect/quiz': typeof ProtectQuizRoute
  '/rent/apply': typeof RentApplyRoute
  '/rent/calendar': typeof RentCalendarRoute
  '/rent/desk': typeof RentDeskRoute
  '/rent/leases': typeof RentLeasesRoute
  '/rent/payments': typeof RentPaymentsRoute
  '/rent/waitlist': typeof RentWaitlistRoute
  '/rent/work': typeof RentWorkRoute
  '/protect': typeof ProtectIndexRoute
  '/rent': typeof RentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attorney': typeof AttorneyRoute
  '/connect': typeof ConnectRoute
  '/dash': typeof DashRoute
  '/houses': typeof HousesRoute
  '/hunt': typeof HuntRoute
  '/letters': typeof LettersRoute
  '/owners': typeof OwnersRoute
  '/packet': typeof PacketRoute
  '/protect': typeof ProtectRouteWithChildren
  '/rent': typeof RentRouteWithChildren
  '/search': typeof SearchRoute
  '/protect/crisis': typeof ProtectCrisisRoute
  '/protect/dashboard': typeof ProtectDashboardRoute
  '/protect/fees': typeof ProtectFeesRoute
  '/protect/intake': typeof ProtectIntakeRoute
  '/protect/packet': typeof ProtectPacketRoute
  '/protect/quiz': typeof ProtectQuizRoute
  '/rent/apply': typeof RentApplyRoute
  '/rent/calendar': typeof RentCalendarRoute
  '/rent/desk': typeof RentDeskRoute
  '/rent/leases': typeof RentLeasesRoute
  '/rent/payments': typeof RentPaymentsRoute
  '/rent/waitlist': typeof RentWaitlistRoute
  '/rent/work': typeof RentWorkRoute
  '/protect/': typeof ProtectIndexRoute
  '/rent/': typeof RentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attorney'
    | '/connect'
    | '/dash'
    | '/houses'
    | '/hunt'
    | '/letters'
    | '/owners'
    | '/packet'
    | '/protect'
    | '/rent'
    | '/search'
    | '/protect/crisis'
    | '/protect/dashboard'
    | '/protect/fees'
    | '/protect/intake'
    | '/protect/packet'
    | '/protect/quiz'
    | '/rent/apply'
    | '/rent/calendar'
    | '/rent/desk'
    | '/rent/leases'
    | '/rent/payments'
    | '/rent/waitlist'
    | '/rent/work'
    | '/protect/'
    | '/rent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attorney'
    | '/connect'
    | '/dash'
    | '/houses'
    | '/hunt'
    | '/letters'
    | '/owners'
    | '/packet'
    | '/search'
    | '/protect/crisis'
    | '/protect/dashboard'
    | '/protect/fees'
    | '/protect/intake'
    | '/protect/packet'
    | '/protect/quiz'
    | '/rent/apply'
    | '/rent/calendar'
    | '/rent/desk'
    | '/rent/leases'
    | '/rent/payments'
    | '/rent/waitlist'
    | '/rent/work'
    | '/protect'
    | '/rent'
  id:
    | '__root__'
    | '/'
    | '/attorney'
    | '/connect'
    | '/dash'
    | '/houses'
    | '/hunt'
    | '/letters'
    | '/owners'
    | '/packet'
    | '/protect'
    | '/rent'
    | '/search'
    | '/protect/crisis'
    | '/protect/dashboard'
    | '/protect/fees'
    | '/protect/intake'
    | '/protect/packet'
    | '/protect/quiz'
    | '/rent/apply'
    | '/rent/calendar'
    | '/rent/desk'
    | '/rent/leases'
    | '/rent/payments'
    | '/rent/waitlist'
    | '/rent/work'
    | '/protect/'
    | '/rent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttorneyRoute: typeof AttorneyRoute
  ConnectRoute: typeof ConnectRoute
  DashRoute: typeof DashRoute
  HousesRoute: typeof HousesRoute
  HuntRoute: typeof HuntRoute
  LettersRoute: typeof LettersRoute
  OwnersRoute: typeof OwnersRoute
  PacketRoute: typeof PacketRoute
  ProtectRoute: typeof ProtectRouteWithChildren
  RentRoute: typeof RentRouteWithChildren
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attorney': {
      id: '/attorney'
      path: '/attorney'
      fullPath: '/attorney'
      preLoaderRoute: typeof AttorneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunt': {
      id: '/hunt'
      path: '/hunt'
      fullPath: '/hunt'
      preLoaderRoute: typeof HuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet': {
      id: '/packet'
      path: '/packet'
      fullPath: '/packet'
      preLoaderRoute: typeof PacketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect/': {
      id: '/protect/'
      path: '/'
      fullPath: '/protect/'
      preLoaderRoute: typeof ProtectIndexRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/protect/crisis': {
      id: '/protect/crisis'
      path: '/crisis'
      fullPath: '/protect/crisis'
      preLoaderRoute: typeof ProtectCrisisRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/protect/dashboard': {
      id: '/protect/dashboard'
      path: '/dashboard'
      fullPath: '/protect/dashboard'
      preLoaderRoute: typeof ProtectDashboardRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/protect/fees': {
      id: '/protect/fees'
      path: '/fees'
      fullPath: '/protect/fees'
      preLoaderRoute: typeof ProtectFeesRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/protect/intake': {
      id: '/protect/intake'
      path: '/intake'
      fullPath: '/protect/intake'
      preLoaderRoute: typeof ProtectIntakeRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/protect/packet': {
      id: '/protect/packet'
      path: '/packet'
      fullPath: '/protect/packet'
      preLoaderRoute: typeof ProtectPacketRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/protect/quiz': {
      id: '/protect/quiz'
      path: '/quiz'
      fullPath: '/protect/quiz'
      preLoaderRoute: typeof ProtectQuizRouteImport
      parentRoute: typeof ProtectRoute
    }
    '/rent/': {
      id: '/rent/'
      path: '/'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/apply': {
      id: '/rent/apply'
      path: '/apply'
      fullPath: '/rent/apply'
      preLoaderRoute: typeof RentApplyRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/calendar': {
      id: '/rent/calendar'
      path: '/calendar'
      fullPath: '/rent/calendar'
      preLoaderRoute: typeof RentCalendarRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/desk': {
      id: '/rent/desk'
      path: '/desk'
      fullPath: '/rent/desk'
      preLoaderRoute: typeof RentDeskRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/leases': {
      id: '/rent/leases'
      path: '/leases'
      fullPath: '/rent/leases'
      preLoaderRoute: typeof RentLeasesRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/payments': {
      id: '/rent/payments'
      path: '/payments'
      fullPath: '/rent/payments'
      preLoaderRoute: typeof RentPaymentsRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/waitlist': {
      id: '/rent/waitlist'
      path: '/waitlist'
      fullPath: '/rent/waitlist'
      preLoaderRoute: typeof RentWaitlistRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/work': {
      id: '/rent/work'
      path: '/work'
      fullPath: '/rent/work'
      preLoaderRoute: typeof RentWorkRouteImport
      parentRoute: typeof RentRoute
    }
  }
}

interface ProtectRouteChildren {
  ProtectCrisisRoute: typeof ProtectCrisisRoute
  ProtectDashboardRoute: typeof ProtectDashboardRoute
  ProtectFeesRoute: typeof ProtectFeesRoute
  ProtectIntakeRoute: typeof ProtectIntakeRoute
  ProtectPacketRoute: typeof ProtectPacketRoute
  ProtectQuizRoute: typeof ProtectQuizRoute
  ProtectIndexRoute: typeof ProtectIndexRoute
}

const ProtectRouteChildren: ProtectRouteChildren = {
  ProtectCrisisRoute: ProtectCrisisRoute,
  ProtectDashboardRoute: ProtectDashboardRoute,
  ProtectFeesRoute: ProtectFeesRoute,
  ProtectIntakeRoute: ProtectIntakeRoute,
  ProtectPacketRoute: ProtectPacketRoute,
  ProtectQuizRoute: ProtectQuizRoute,
  ProtectIndexRoute: ProtectIndexRoute,
}

const ProtectRouteWithChildren =
  ProtectRoute._addFileChildren(ProtectRouteChildren)

interface RentRouteChildren {
  RentApplyRoute: typeof RentApplyRoute
  RentCalendarRoute: typeof RentCalendarRoute
  RentDeskRoute: typeof RentDeskRoute
  RentLeasesRoute: typeof RentLeasesRoute
  RentPaymentsRoute: typeof RentPaymentsRoute
  RentWaitlistRoute: typeof RentWaitlistRoute
  RentWorkRoute: typeof RentWorkRoute
  RentIndexRoute: typeof RentIndexRoute
}

const RentRouteChildren: RentRouteChildren = {
  RentApplyRoute: RentApplyRoute,
  RentCalendarRoute: RentCalendarRoute,
  RentDeskRoute: RentDeskRoute,
  RentLeasesRoute: RentLeasesRoute,
  RentPaymentsRoute: RentPaymentsRoute,
  RentWaitlistRoute: RentWaitlistRoute,
  RentWorkRoute: RentWorkRoute,
  RentIndexRoute: RentIndexRoute,
}

const RentRouteWithChildren = RentRoute._addFileChildren(RentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttorneyRoute: AttorneyRoute,
  ConnectRoute: ConnectRoute,
  DashRoute: DashRoute,
  HousesRoute: HousesRoute,
  HuntRoute: HuntRoute,
  LettersRoute: LettersRoute,
  OwnersRoute: OwnersRoute,
  PacketRoute: PacketRoute,
  ProtectRoute: ProtectRouteWithChildren,
  RentRoute: RentRouteWithChildren,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
